user: idb
group: idb
vendor: bytemine GmbH
maintainer: info@bytemine.net
homepage: https://www.bytemine.net/
targets:
  centos-7:
   build_dependencies:
      - mysql-devel
      - libxml2-devel
      - libxslt
      - libxslt-devel
   dependencies:
      - redis 
      - mariadb-server 
      - mod_ssl 
      - httpd-devel 
      - postfix 
      - mod_passenger 
      - passenger-devel 
      - vim 
      - libevent 
      - postgresql-libs 
  ubuntu-14.04:
    build_dependencies:
      - libgmp-dev 
      - build-essential 
      - bison 
      - openssl 
      - libreadline6
      - libreadline6-dev 
      - curl 
      - git-core 
      - zlib1g 
      - zlib1g-dev 
      - libssl-dev 
      - libyaml-dev 
      - libxml2-dev
      - autoconf 
      - libc6-dev 
      - ncurses-dev 
      - automake 
      - libtool 
      - libmysqlclient-dev 
      - mysql-client
      - libxslt1.1
      - libxslt1-dev 
      - mysql-server
    dependencies:
      - apache2
      - mysql-server
      - redis-server
      - vim
      - postfix
      - libapache2-mod-passenger
